apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: superbigtool
        tier: api
    spec:
      containers:
        - name: api
          image: quay.io/superbigtool/api:2.1.0
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_DATABASE
              value: supertool
            - name: POSTGRES_POOL_SIZE
              value: 50
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PORT
            - name: HMAC_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: HMAC_SECRET
