apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: superbigtool
    tier: api
spec:
  type: NodePort
  ports:
  - name: svcmain
    targetPort: 3000
  selector:
    app: superbigtool
    tier: api
